### PR TITLE
Add ZipOption to preserve symbolic links

### PR DESCRIPTION
**Pull request by blender**
This pull request adds support for symbolic links.

Similar to `zip -r -q --symlinks zipWithSymLinks.zip dir/` just leave symlinks as they are by:
- if symlink is a directory: don't recurse into it and as compresseData put the symlink target path
- if symlink is a file: as compresseData put the symlink target path
- set filemode to symlink

~~I am not sure how to get this working (or to ignore this) on Windows as I don't have access to a windows machine.~~ The option is ignored on Windows.

See https://github.com/blender/Rome/issues/112 for motivation

### CODE REVIEW

**Comment by blender** [comment]
@jgm any feedback on this?

**Comment by jgm** [comment]
Looks good!  Can we get some tests for this feature, though?  See `tests/test-zip-archive.hs`.

**Comment by blender** [comment]
@jgm I have expanded `testAddFilesOptions`

Please let me know if you think more tests are in order.

I also added the note that OptsPreserveSymlinks is ignored on Windows.

**Comment by blender** [comment]
- Fixed problem with CRC32
- simplified code
- added more test (CI failed because of network, not because of testes(

**Comment by jgm** [comment]
Thanks, I've merged this!

One question:  is there really a good reason to put this under an option?  We could just make it the default to preserve symbolic links on systems that support them.

**Comment by blender** [comment]
@jgm  good question. The command line utility does have it as an option (--symlinks)

Apparently some times people do want to copy the content of target of the symlinks into the destination. Beasts me why though.

Also, the only reason why I could not implement it for Windows was because I didn't find an equivalent of `POSIX.isSymlickLink` and `directory.pathIsSymbolicLink` is not available in older LTS.

If you want to suggest a way forward I could also try to implement it for Windows.

**Pull request merged**
